
name: build

on:
  push:
    paths:
      - ".github/workflows/*"
      - "."
  workflow_dispatch: # manual

jobs:
  build:
    name: build-dotnet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
        working-directory: ./
    #   - run: dotnet test
    #     working-directory: ./*



# *** notes:
# steps[*].working-directory: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory
# path filter globs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
