name: Build and Deploy .NET App

on:
  push:
    paths:
      - main
  workflow_dispatch: # manual

jobs:
    build-job:
        runs-on: windows-latest

        steps:
            
            - name: checkout code
              uses: action/checkout@v4

            - name: Set up .NET core
              uses: action:/setup-dotnet@v4
              with:
                dotnet-version: '8.x'
            
            - name: Publish code
              run: dotnet publish -c Release --property:PublishDir="${{ runner.temp }}\myapp"
        
            - name: Upload Artifact
              uses: actions/upload-artifact@v4.3.6
              with:
                # Artifact name
                name: .net-app
                path: ${{ runner.temp }}/myapp

    deploy-job:
        runs-on: windows-latest
        needs: build-job
        env:
          package-name: .net-app
          app-name: azureapp1
          deployment-slot: production
        
        steps:

           - name: Download artifact from build job
             uses: actions/download-artifact@v4.1.8
             with:
               name: ${{ inputs.package-name }}
    
           - name: Secret Information
             run: echo "Value of secret matches - ${{ secrets.azure-profile  == 'Placeholder' }}"
    
           - name: Print name of App Service to deploy to
             run: echo "App will be deployed to ${{ inputs.app-name }}"
          
           - name: List files in root directory
             run: |
               Get-ChildItem -Path . | ForEach-Object { Write-Output $_.Name }
             shell: pwsh

        
    

